## ======================================================================
## Pipeline for GPDB gphdfs
## ======================================================================

resources:
- name: gpdb_src
  type: git
  source:
    branch: {{gphdfs-git-branch}}
    private_key: {{gpdb-git-key}}
    uri: {{gphdfs-git-remote}}
- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'
    username: {{docker_username}}
    password: {{docker_password}}
- name: bin_gpdb_centos
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: bin_gpdb_centos/bin_gpdb.tar.gz
- name: sync_tools_gpdb_centos
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: {{bucket-name}}
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: sync_tools_gpdb_centos/sync_tools_gpdb.tar.gz

jobs:
- name: regression_tests_gphdfs_centos
  plan:
  - aggregate:
    - get: gpdb_src
      trigger: true
    - get: sync_tools_gpdb_centos
      resource: sync_tools_gpdb_centos
    - get: bin_gpdb
      resource: bin_gpdb_centos
    - get: centos-gpdb-dev-6
  - task: regression_tests_gphdfs
    file: gpdb_src/concourse/tasks/regression_tests_gphdfs.yml
    image: centos-gpdb-dev-6
    params:
      TARGET_OS: centos
      TARGET_OS_VERSION: 6
