resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

resources:
  - name: gpdb_pr
    type: pull-request
    source:
      repository: greenplum-db/gpdb
      access_token: ((gpdb-git-access-token))
      base_branch: "5X_STABLE"
      ignore_paths:
        - gpdb-doc/*
        - README*

  - name: gpdb_5x_upstream
    type: git
    source:
      uri: https://github.com/greenplum-db/gpdb
      branch: "5X_STABLE"

  - name: gpaddon_src
    type: git
    source:
      branch: {{gpaddon-git-branch}}
      private_key: {{gpaddon-git-key}}
      uri: {{gpaddon-git-remote}}

  - name: centos-gpdb-dev-6
    type: docker-image
    source:
      repository: pivotaldata/centos-gpdb-dev
      tag: '6-gcc6.2-llvm3.7'

  - name: binary_swap_gpdb_centos6
    type: s3
    source:
      access_key_id: {{bucket-access-key-id}}
      bucket: {{bucket-name}}
      region_name: {{aws-region}}
      secret_access_key: {{bucket-secret-access-key}}
      versioned_file: {{binary_swap_gpdb_centos_versioned_file}}

jobs:
  - name: compile-and-test-pull-request
    plan:
      - in_parallel:
          - get: gpdb_pr
            version: every
            trigger: true
          - get: binary_swap_gpdb
            resource: binary_swap_gpdb_centos6
            trigger: true
          - get: centos-gpdb-dev-6
          - get: gpaddon_src
          - get: gpdb_5x_upstream
      # We use the 5X_STABLE source for running make sync_tools instead for security.
      # For example, this would prevent a user to submit a PR that maliciously
      # modifies the sync_tools task to expose the ivy credentials.
      - task: sync_tools
        input_mapping:
          gpdb_src: gpdb_5x_upstream
        file: gpdb_5x_upstream/concourse/tasks/sync_tools.yml
        image: centos-gpdb-dev-6
        params:
          IVYREPO_HOST: {{ivyrepo_host}}
          IVYREPO_REALM: {{ivyrepo_realm}}
          IVYREPO_USER: {{ivyrepo_user}}
          IVYREPO_PASSWD: {{ivyrepo_passwd}}
          TARGET_OS: centos
          TARGET_OS_VERSION: 6
          TASK_OS: centos
          TASK_OS_VERSION: 6

      - task: compile_gpdb
        input_mapping:
          gpdb_src: gpdb_pr
        file: gpdb_pr/concourse/tasks/compile_gpdb.yml
        image: centos-gpdb-dev-6
        params:
          CONFIGURE_FLAGS: {{configure_flags}}
          TARGET_OS: centos
          TARGET_OS_VERSION: 6
          BLD_TARGETS: "clients loaders"

      - in_parallel:
        - put: gpdb_pr
          params:
            path: gpdb_pr
            status: pending
        - task: ic_gpdb
          file: gpdb_pr/concourse/tasks/ic_gpdb_binary_swap.yml
          image: centos-gpdb-dev-6
          input_mapping:
            gpdb_src: gpdb_pr
            bin_gpdb: gpdb_artifacts
          params:
            MAKE_TEST_COMMAND: PGOPTIONS='-c optimizer=off' installcheck-world
            BLDWRAP_POSTGRES_CONF_ADDONS: "fsync=off"
            TEST_OS: centos
            CONFIGURE_FLAGS: {{configure_flags}}

      - put: report_pr_success
        resource: gpdb_pr
        params:
          path: gpdb_pr
          status: success
