SELECT CURRENT_TIMESTAMP;

create table subt_for_ctas_ao(i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with (appendonly=true) distributed randomly;
Insert into subt_for_ctas_ao values(generate_series(1,5),'table used for ctas','s','subtransaction table','12-11-2012',3,'2012-10-09 10:23:54', '2011-08-19 10:23:54+02');
-- Values to be inserted in the transactions below are in this table. Not using
-- directly VALUES clause or generate_series() because the reader gang where we
-- intend to inject fault need to happen on the segments. The VALUES clause or
-- generate_series() usage doesn't guarantee such a plan.
create temp table subtransaction_temp (like subt_for_ctas_ao);
Insert into subtransaction_temp values(generate_series(1,4),'create table with subtransactions','s','subtransaction table','12-11-2012',3,'2012-10-09 10:23:54', '2011-08-19 10:23:54+02');
BEGIN;
Savepoint sp1;
Create table subt_tab_distby_ao1 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Savepoint sp2;
Create table subt_tab_distby_ao2 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao1 select * from subtransaction_temp;
Savepoint sp3;
Create table subt_tab_distby_ao3 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao2 select * from subtransaction_temp;
Savepoint sp4;
Create table subt_tab_distby_ao4 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao3 select * from subtransaction_temp;
Savepoint sp5;
Create table subt_tab_distby_ao5 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao4 select * from subtransaction_temp;
Savepoint sp6;
Create table subt_tab_distby_ao6 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao5 select * from subtransaction_temp;
Savepoint sp7;
Create table subt_tab_distby_ao7 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao6 select * from subtransaction_temp;
Savepoint sp8;
Create table subt_tab_distby_ao8 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao7 select * from subtransaction_temp;
Savepoint sp9;
Create table subt_tab_distby_ao9 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao8 select * from subtransaction_temp;
Savepoint sp10;
Create table subt_tab_distby_ao10 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao9 select * from subtransaction_temp;
Savepoint sp11;
Create table subt_tab_distby_ao11 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao10 select * from subtransaction_temp;
Savepoint sp12;
Create table subt_tab_distby_ao12 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao11 select * from subtransaction_temp;
Savepoint sp13;
Create table subt_tab_distby_ao13 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao12 select * from subtransaction_temp;
Savepoint sp14;
Create table subt_tab_distby_ao14 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao13 select * from subtransaction_temp;
Savepoint sp15;
Create table subt_tab_distby_ao15 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao14 select * from subtransaction_temp;
Savepoint sp16;
Create table subt_tab_distby_ao16 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao15 select * from subtransaction_temp;
Savepoint sp17;
Create table subt_tab_distby_ao17 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao16 select * from subtransaction_temp;
Savepoint sp18;
Create table subt_tab_distby_ao18 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao17 select * from subtransaction_temp;
Savepoint sp19;
Create table subt_tab_distby_ao19 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao18 select * from subtransaction_temp;
Savepoint sp20;
Create table subt_tab_distby_ao20 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao19 select * from subtransaction_temp;
Savepoint sp21;
Create table subt_tab_distby_ao21 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao20 select * from subtransaction_temp;
Savepoint sp22;
Create table subt_tab_distby_ao22 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao21 select * from subtransaction_temp;
Savepoint sp23;
Create table subt_tab_distby_ao23 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao22 select * from subtransaction_temp;
Savepoint sp24;
Create table subt_tab_distby_ao24 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao23 select * from subtransaction_temp;
Savepoint sp25;
Create table subt_tab_distby_ao25 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao24 select * from subtransaction_temp;
Savepoint sp26;
Create table subt_tab_distby_ao26 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao25 select * from subtransaction_temp;
Savepoint sp27;
Create table subt_tab_distby_ao27 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao26 select * from subtransaction_temp;
Savepoint sp28;
Create table subt_tab_distby_ao28 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao27 select * from subtransaction_temp;
Savepoint sp29;
Create table subt_tab_distby_ao29 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao28 select * from subtransaction_temp;
Savepoint sp30;
Create table subt_tab_distby_ao30 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao29 select * from subtransaction_temp;
Savepoint sp31;
Create table subt_tab_distby_ao31 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao30 select * from subtransaction_temp;
Savepoint sp32;
Create table subt_tab_distby_ao32 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao31 select * from subtransaction_temp;
Savepoint sp33;
Create table subt_tab_distby_ao33 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao32 select * from subtransaction_temp;
Savepoint sp34;
Create table subt_tab_distby_ao34 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao33 select * from subtransaction_temp;
Savepoint sp35;
Create table subt_tab_distby_ao35 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao34 select * from subtransaction_temp;
Savepoint sp36;
Create table subt_tab_distby_ao36 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao35 select * from subtransaction_temp;
Savepoint sp37;
Create table subt_tab_distby_ao37 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao36 select * from subtransaction_temp;
Savepoint sp38;
Create table subt_tab_distby_ao38 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao37 select * from subtransaction_temp;
Savepoint sp39;
Create table subt_tab_distby_ao39 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao38 select * from subtransaction_temp;
Savepoint sp40;
Create table subt_tab_distby_ao40 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao39 select * from subtransaction_temp;
Savepoint sp41;
Create table subt_tab_distby_ao41 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao40 select * from subtransaction_temp;
Release Savepoint sp41;
Savepoint sp42;
Create table subt_tab_distby_ao42 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao41 select * from subtransaction_temp;
Release Savepoint sp42;
Savepoint sp43;
Create table subt_tab_distby_ao43 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao42 select * from subtransaction_temp;
Release Savepoint sp43;
Savepoint sp44;
Create table subt_tab_distby_ao44 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao43 select * from subtransaction_temp;
Release Savepoint sp44;
Savepoint sp45;
Create table subt_tab_distby_ao45 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao44 select * from subtransaction_temp;
Release Savepoint sp45;
Savepoint sp46;
Create table subt_tab_distby_ao46 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao45 select * from subtransaction_temp;
Release Savepoint sp46;
Savepoint sp47;
Create table subt_tab_distby_ao47 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao46 select * from subtransaction_temp;
Release Savepoint sp47;
Savepoint sp48;
Create table subt_tab_distby_ao48 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao47 select * from subtransaction_temp;
Release Savepoint sp48;
Savepoint sp49;
Create table subt_tab_distby_ao49 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao48 select * from subtransaction_temp;
Release Savepoint sp49;
Savepoint sp50;
Create table subt_tab_distby_ao50 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao49 select * from subtransaction_temp;
Release Savepoint sp50;
Savepoint sp51;
Create table subt_tab_distby_ao51 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao50 select * from subtransaction_temp;
Release Savepoint sp51;
Savepoint sp52;
Create table subt_tab_distby_ao52 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao51 select * from subtransaction_temp;
Release Savepoint sp52;
Savepoint sp53;
Create table subt_tab_distby_ao53 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao52 select * from subtransaction_temp;
Release Savepoint sp53;
Savepoint sp54;
Create table subt_tab_distby_ao54 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao53 select * from subtransaction_temp;
Release Savepoint sp54;
Savepoint sp55;
Create table subt_tab_distby_ao55 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao54 select * from subtransaction_temp;
Release Savepoint sp55;
Savepoint sp56;
Create table subt_tab_distby_ao56 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao55 select * from subtransaction_temp;
Release Savepoint sp56;
Savepoint sp57;
Create table subt_tab_distby_ao57 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao56 select * from subtransaction_temp;
Release Savepoint sp57;
Savepoint sp58;
Create table subt_tab_distby_ao58 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao57 select * from subtransaction_temp;
Rollback to sp58;
Savepoint sp59;
Create table subt_tab_distby_ao59 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Release Savepoint sp59;
Savepoint sp60;
Create table subt_tab_distby_ao60 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao59 select * from subtransaction_temp;
Release Savepoint sp60;
Savepoint sp61;
Create table subt_tab_distby_ao61 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao60 select * from subtransaction_temp;
Release Savepoint sp61;
Savepoint sp62;
Create table subt_tab_distby_ao62 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao61 select * from subtransaction_temp;
Release Savepoint sp62;
Savepoint sp63;
Create table subt_tab_distby_ao63 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao62 select * from subtransaction_temp;
Release Savepoint sp63;
Savepoint sp64;
Create table subt_tab_distby_ao64 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao63 select * from subtransaction_temp;
Release Savepoint sp64;
Savepoint sp65;
Create table subt_tab_distby_ao65 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao64 select * from subtransaction_temp;
Release Savepoint sp65;
Savepoint sp66;
Create table subt_tab_distby_ao66 (i int, x text,c char,v varchar, d date, n numeric, t timestamp without time zone, tz time with time zone) with(appendonly=true) distributed by (i);
Insert into subt_tab_distby_ao65 select * from subtransaction_temp;
Release Savepoint sp66;
COMMIT;

SELECT CURRENT_TIMESTAMP;

