#!/usr/bin/env bash

newopts=""

for opt in $*
do
	case $opt in
	-O*|-g*)
		## We ignore any -O or -g options.
	;;
	*)
		newopts="$newopts $opt"
	;;
	esac
done

## Append -g3 -Og to compilation flags, since abi-dumper requires them.
exec env PATH=$(echo "$PATH" | sed -e "s/${GCC_WRAPPER}://") "$(which gcc)" -g3 -Og $*
