#!/usr/bin/env bash

set -x

newopts=()

opt_option=false

for opt in $*
do
	case $opt in
	-O*|-g*)
		## We ignore any -O or -g options.
		opt_option=true
	;;
	*)
		newopts+=($opt)
	;;
	esac
done

if [[ $opt_option == true ]];; then
    ## Append -g3 -Og to compilation flags, since abi-dumper requires them.
    env PATH=$(echo "$PATH" | sed -e "s/${GCC_WRAPPER}://") $(which gcc) "-Og -g3 ${newopts[@]}"
else
    env PATH=$(echo "$PATH" | sed -e "s/${GCC_WRAPPER}://") $(which gcc) "${newopts[@]}"
fi
