FROM buildpack-deps:jessie
RUN groupadd -r greenplum --gid=999 && useradd -r -g greenplum --uid=999 greenplum
RUN gpg --keyserver pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4

RUN GOSU_VERSION=1.4 \
 && BUILD_DEPS="git-core \
  gcc g++ \
  ccache \
  libreadline5 \
  libreadline-dev \
  libncurses5-dev \
  bison flex \
  zlib1g-dev \
  openssl libssl-dev \
  libpam-dev \
  libbz2-dev \
  python-dev \
  ssh \
  libcurl4-openssl-dev \
  make cmake \
  curl wget \
  unzip \
  pgxnclient \
  python-pip \
  ruby ruby-dev \
  ca-certificates \
  " \
 && apt-get update \
 && apt-get install -y --no-install-recommends $BUILD_DEPS \
 && gem install fpm --no-ri --no-rdoc \
 && rm -rf /var/lib/apt/lists/* \
 && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" \
 && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" \
 && gpg --verify /usr/local/bin/gosu.asc \
 && rm /usr/local/bin/gosu.asc \
 && chmod +x /usr/local/bin/gosu

RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
	&& localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8

ADD docker/docker_entrypoint.sh /docker_entrypoint.sh
RUN chmod +x /docker_entrypoint.sh
ENTRYPOINT [ "/docker_entrypoint.sh" ]
CMD [ "build" ]
