resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: pivotaldata/pr-resource

resources:
  - name: gpdb_pr
    type: pull-request
    source:
      repo: greenplum-db/gpdb
      access_token: {{gpdb_access_token}}

  - name: gpos_github_release
    type: github-release
    source:
      user: greenplum-db
      repository: gpos
      access_token: {{gposbot_access_token}}

  - name: orca_github_release
    type: github-release
    source:
      user: greenplum-db
      repository: gporca
      access_token: {{gporcabot_access_token}}

  - name: bin_xerces
    type: s3
    source:
      access_key_id: {{aws-access-key-id}}
      bucket: {{bucket-name}}
      region_name: {{aws-region}}
      secret_access_key: {{aws-secret-access-key}}
      versioned_file: bin_xerces_centos5.tar.gz

  - name: bin_gpdb
    type: s3
    source:
      access_key_id: {{aws-access-key-id}}
      bucket: gporca-concourse-bucket
      region_name: {{aws-region}}
      secret_access_key: {{aws-secret-access-key}}
      versioned_file: bin_gpdb_with_orca_centos6.tar.gz

  - name: regression_diffs
    type: s3
    source:
       access_key_id: {{aws-access-key-id}}
       bucket: {{bucket-name}}
       region_name: {{aws-region}}
       secret_access_key: {{aws-secret-access-key}}
       versioned_file: regression.diffs

  - name: regression_out
    type: s3
    source:
       access_key_id: {{aws-access-key-id}}
       bucket: {{bucket-name}}
       region_name: {{aws-region}}
       secret_access_key: {{aws-secret-access-key}}
       versioned_file: regression.out


jobs:
  - name: build_with_orca
    plan:
      - aggregate:
        - get: gpos_github_release
          params:
            globs:
              - bin_gpos_centos5_release.tar.gz
        - get: orca_github_release
          params:
            globs:
              - bin_orca_centos5_release.tar.gz
        - get: bin_xerces
        - get: gpdb_pr
          trigger: true
      # update the PR status as pending
      - put: gpdb_pr
        params:
          path: gpdb_pr
          status: pending
      - task: build_with_orca
        file: gpdb_pr/concourse/build_with_orca.yml
        input_mapping:
          gpdb_src: gpdb_pr
          bin_orca: orca_github_release
          bin_gpos: gpos_github_release
        on_success:
          # update the PR status as pending
          put: gpdb_pr
          params:
            path: gpdb_pr
            status: pending
        on_failure:
          put: gpdb_pr
          params:
            path: gpdb_pr
            status: failure
      - task: package_tarball
        file: gpdb_pr/concourse/package_tarball.yml
        input_mapping:
          gpdb_src: gpdb_pr
        on_success:
          put: gpdb_pr
          params:
            path: gpdb_pr
            status: pending
        on_failure:
          put: gpdb_pr
          params:
            path: gpdb_pr
            status: failure
      - put: bin_gpdb
        params:
          file: package_tarball/bin_gpdb.tar.gz


  - name: icg
    plan:
      - aggregate:
        - get: gpos_github_release
          params:
            globs:
              - bin_gpos_centos5_release.tar.gz
          passed:
            - build_with_orca
        - get: orca_github_release
          params:
            globs:
              - bin_orca_centos5_release.tar.gz
          passed:
            - build_with_orca
        - get: bin_xerces
          passed:
            - build_with_orca
        - get: bin_gpdb
          passed:
            - build_with_orca
        - get: gpdb_pr
          trigger: true
          passed:
            - build_with_orca
      - put: gpdb_pr
        params:
          path: gpdb_pr
          status: pending
      - task: icg
        file: gpdb_pr/concourse/test_with_orca.yml
        input_mapping:
          gpdb_src: gpdb_pr
          bin_orca: orca_github_release
          bin_gpos: gpos_github_release
        timeout: 2h30m
        on_success:
          put: gpdb_pr
          params:
            path: gpdb_pr
            status: success
        on_failure:
          aggregate:
          - put: regression_diffs
            params:
              from: icg_output/regression.diffs
          - put: regression_out
            params:
              from: icg_output/regression.out
          - put: gpdb_pr
            params:
              path: gpdb_pr
              status: failure
