platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-orca/qp-gpdbdev
inputs:
  - name: bin_orca
  - name: bin_xerces
  - name: gpdb_src
outputs:
  - name: bin_gpdb
params:
  MODE:
  OUTPUTDIR:
  ACTION:
  CONFIGURE_OPTION:
  OTHER_CONFIGS:
run:
  path: sh
  args:
  - -exc
  - |
    gpdb_src/concourse/scripts/build_gpdb.py ${MODE} ${OUTPUTDIR} ${ACTION} ${CONFIGURE_OPTION} ${OTHER_CONFIGS}
