platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: pxf_src
  - name: pxf_gradle_dependencies
outputs:
  - name: pxf_artifacts
run:
  path: gpdb_src/concourse/scripts/compile_pxf.bash
params:
  TARGET_OS:
  TARGET_OS_VERSION:
  BLD_TARGETS:
  OUTPUT_ARTIFACT_DIR: pxf_artifacts
