---
platform: linux

image_resource:
  type: registry-image

inputs:
- name: gpdb_src
- name: gpaddon_src
- name: gpdb_artifacts

outputs:
- name: gpAux_ext
- name: gphdfs_dist


run:
  path: gpdb_src/concourse/scripts/sync_tools.bash
