platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/data-orca/qp-gpdbdev
inputs:
  - name: gpdb_src
  - name: bin_orca
  - name: bin_xerces
  - name: bin_gpdb
outputs:
  - name: icg_output
params:
  BLDWRAP_POSTGRES_CONF_ADDONS:
  MODE:
  ACTION:
  CONFIGURE_OPTION:
  GPDB_BINARY:
run:
  path: sh
  args:
  - -exc
  - |
    gpdb_src/concourse/scripts/build_gpdb.py ${MODE} ${ACTION} ${CONFIGURE_OPTION} ${GPDB_BINARY}
