platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/qp-gpdbdev
inputs:
  - name: gpdb_src
  - name: bin_orca
  - name: bin_xerces
  - name: bin_gpdb
  - name: gpdb_main_src
  - name: explain_test_suite
outputs:
  - name: icg_output
run:
  path: gpdb_main_src/concourse/scripts/build_gpdb.py
  args:
    - --mode=orca
    - --gpdb_name=bin_gpdb
    - --action=test_explain_suite
    - --configure-option=--disable-gpcloud
params:
  BLDWRAP_POSTGRES_CONF_ADDONS: statement_mem=250MB
