platform: linux
image_resource:
  type: docker-image
  source:
    repository: pivotaldata/centos67-gpdb-gcc6-llvm-image
    username:
    password:
    email:
inputs:
  - name: gpdb_src
run:
  path: gpdb_src/concourse/scripts/unit_tests_gpcloud.bash
