platform: linux
image_resource:
  type: registry-image
inputs:
  - name: gpdb_src
run:
  path: gpdb_src/concourse/scripts/validate_pipeline_release_jobs.py
params:
  PIPELINE_FILE: gpdb_src/concourse/pipelines/pipeline.yml
