google-region: us-central1
google-project-id: data-sandbox-2
gcs-bucket: pivotal-gpdb-concourse-resources-dev
gcs-bucket-intermediates: pivotal-gpdb-concourse-resources-intermediates-dev
gpdb-stable-builds-bucket-name: gpdb-stable-concourse-builds-dev
bucket-name: gpdb-stable-concourse-builds-dev

