/*-------------------------------------------------------------------------
 *
 * kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef KWLIST_D_H
#define KWLIST_D_H

#include "common/kwlookup.h"

static const char ScanKeywords_kw_string[] =
	"abort\0"
	"absolute\0"
	"access\0"
	"action\0"
	"active\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"array\0"
	"as\0"
	"asc\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"attach\0"
	"attribute\0"
	"authorization\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"bit\0"
	"boolean\0"
	"both\0"
	"by\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"concurrency\0"
	"concurrently\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"contains\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"coordinator\0"
	"copy\0"
	"cost\0"
	"cpu_rate_limit\0"
	"cpuset\0"
	"create\0"
	"createexttable\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"day\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"deny\0"
	"depends\0"
	"desc\0"
	"detach\0"
	"dictionary\0"
	"disable\0"
	"discard\0"
	"distinct\0"
	"distributed\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"dxl\0"
	"each\0"
	"else\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"end\0"
	"endpoint\0"
	"enum\0"
	"errors\0"
	"escape\0"
	"event\0"
	"every\0"
	"except\0"
	"exchange\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"expand\0"
	"explain\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fetch\0"
	"fields\0"
	"fill\0"
	"filter\0"
	"first\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"format\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"fullscan\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"group_id\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"hash\0"
	"having\0"
	"header\0"
	"hold\0"
	"host\0"
	"hour\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"inclusive\0"
	"increment\0"
	"index\0"
	"indexes\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"initplan\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invoker\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"join\0"
	"key\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"level\0"
	"like\0"
	"limit\0"
	"list\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"log\0"
	"logged\0"
	"mapping\0"
	"master\0"
	"match\0"
	"materialized\0"
	"maxvalue\0"
	"median\0"
	"memory_limit\0"
	"memory_shared_quota\0"
	"memory_spill_ratio\0"
	"method\0"
	"minute\0"
	"minvalue\0"
	"missing\0"
	"mode\0"
	"modifies\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"new\0"
	"newline\0"
	"next\0"
	"no\0"
	"nocreateexttable\0"
	"none\0"
	"noovercommit\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"numeric\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"on\0"
	"only\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordered\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overcommit\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"parallel\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"percent\0"
	"persistently\0"
	"placing\0"
	"plans\0"
	"policy\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"program\0"
	"protocol\0"
	"publication\0"
	"queue\0"
	"quote\0"
	"randomly\0"
	"range\0"
	"read\0"
	"readable\0"
	"reads\0"
	"real\0"
	"reassign\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"reindex\0"
	"reject\0"
	"relative\0"
	"release\0"
	"rename\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"replicated\0"
	"reset\0"
	"resource\0"
	"restart\0"
	"restrict\0"
	"retrieve\0"
	"returning\0"
	"returns\0"
	"revoke\0"
	"right\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"rootpartition\0"
	"routine\0"
	"routines\0"
	"row\0"
	"rows\0"
	"rule\0"
	"savepoint\0"
	"scatter\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"segment\0"
	"segments\0"
	"select\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"show\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"split\0"
	"sql\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"strip\0"
	"subpartition\0"
	"subscription\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysid\0"
	"system\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"text\0"
	"then\0"
	"threshold\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"unbounded\0"
	"uncommitted\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlogged\0"
	"until\0"
	"update\0"
	"user\0"
	"using\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validation\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"volatile\0"
	"web\0"
	"when\0"
	"where\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"writable\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"year\0"
	"yes\0"
	"zone";

static const uint16 ScanKeywords_kw_offsets[] = {
	0,
	6,
	15,
	22,
	29,
	36,
	40,
	46,
	52,
	62,
	66,
	71,
	77,
	84,
	92,
	100,
	104,
	108,
	114,
	117,
	121,
	131,
	142,
	153,
	156,
	163,
	173,
	187,
	196,
	203,
	209,
	217,
	224,
	231,
	235,
	243,
	248,
	251,
	257,
	262,
	269,
	277,
	286,
	291,
	296,
	304,
	310,
	315,
	325,
	341,
	347,
	358,
	364,
	370,
	378,
	387,
	395,
	405,
	412,
	420,
	428,
	437,
	444,
	454,
	466,
	479,
	493,
	502,
	513,
	524,
	536,
	545,
	553,
	562,
	573,
	585,
	590,
	595,
	610,
	617,
	624,
	639,
	645,
	649,
	654,
	662,
	678,
	691,
	704,
	719,
	732,
	750,
	763,
	770,
	776,
	781,
	790,
	794,
	805,
	809,
	817,
	825,
	832,
	840,
	849,
	860,
	869,
	877,
	884,
	894,
	905,
	910,
	918,
	923,
	930,
	941,
	949,
	957,
	966,
	978,
	981,
	990,
	997,
	1004,
	1009,
	1013,
	1018,
	1023,
	1030,
	1039,
	1049,
	1053,
	1062,
	1067,
	1074,
	1081,
	1087,
	1093,
	1100,
	1109,
	1117,
	1127,
	1137,
	1145,
	1152,
	1159,
	1167,
	1177,
	1186,
	1194,
	1200,
	1207,
	1213,
	1220,
	1225,
	1232,
	1238,
	1244,
	1254,
	1258,
	1264,
	1272,
	1279,
	1287,
	1294,
	1299,
	1304,
	1313,
	1322,
	1332,
	1342,
	1349,
	1355,
	1363,
	1372,
	1378,
	1387,
	1396,
	1403,
	1411,
	1416,
	1423,
	1430,
	1435,
	1440,
	1445,
	1454,
	1457,
	1464,
	1470,
	1480,
	1490,
	1499,
	1506,
	1509,
	1517,
	1527,
	1537,
	1547,
	1553,
	1561,
	1569,
	1578,
	1588,
	1597,
	1604,
	1610,
	1616,
	1622,
	1634,
	1641,
	1649,
	1653,
	1661,
	1671,
	1680,
	1685,
	1693,
	1696,
	1703,
	1713,
	1718,
	1722,
	1728,
	1737,
	1743,
	1748,
	1756,
	1764,
	1774,
	1780,
	1785,
	1791,
	1796,
	1802,
	1807,
	1814,
	1819,
	1825,
	1835,
	1850,
	1859,
	1864,
	1871,
	1875,
	1882,
	1890,
	1897,
	1903,
	1916,
	1925,
	1932,
	1945,
	1965,
	1984,
	1991,
	1998,
	2007,
	2015,
	2020,
	2029,
	2035,
	2040,
	2045,
	2051,
	2060,
	2068,
	2074,
	2078,
	2086,
	2091,
	2094,
	2111,
	2116,
	2129,
	2133,
	2141,
	2148,
	2156,
	2163,
	2168,
	2175,
	2181,
	2189,
	2196,
	2199,
	2203,
	2210,
	2215,
	2219,
	2222,
	2227,
	2236,
	2243,
	2251,
	2254,
	2260,
	2268,
	2279,
	2286,
	2290,
	2296,
	2301,
	2312,
	2321,
	2329,
	2340,
	2346,
	2352,
	2361,
	2368,
	2376,
	2386,
	2397,
	2405,
	2414,
	2422,
	2435,
	2443,
	2449,
	2456,
	2465,
	2475,
	2485,
	2493,
	2502,
	2511,
	2519,
	2525,
	2536,
	2547,
	2557,
	2568,
	2576,
	2585,
	2597,
	2603,
	2609,
	2618,
	2624,
	2629,
	2638,
	2644,
	2649,
	2658,
	2666,
	2676,
	2680,
	2691,
	2703,
	2711,
	2719,
	2726,
	2735,
	2743,
	2750,
	2761,
	2769,
	2777,
	2788,
	2794,
	2803,
	2811,
	2820,
	2829,
	2839,
	2847,
	2854,
	2860,
	2865,
	2874,
	2881,
	2895,
	2903,
	2912,
	2916,
	2921,
	2926,
	2936,
	2944,
	2951,
	2959,
	2966,
	2973,
	2980,
	2989,
	2997,
	3006,
	3013,
	3022,
	3032,
	3045,
	3052,
	3060,
	3073,
	3077,
	3083,
	3088,
	3094,
	3099,
	3107,
	3114,
	3119,
	3128,
	3137,
	3142,
	3148,
	3152,
	3159,
	3170,
	3176,
	3186,
	3197,
	3203,
	3210,
	3218,
	3225,
	3232,
	3238,
	3251,
	3264,
	3274,
	3282,
	3292,
	3298,
	3305,
	3311,
	3318,
	3330,
	3341,
	3346,
	3355,
	3365,
	3370,
	3375,
	3385,
	3390,
	3395,
	3405,
	3408,
	3417,
	3429,
	3439,
	3445,
	3453,
	3458,
	3463,
	3472,
	3480,
	3485,
	3491,
	3501,
	3513,
	3525,
	3531,
	3538,
	3546,
	3555,
	3564,
	3570,
	3577,
	3582,
	3588,
	3595,
	3601,
	3610,
	3621,
	3631,
	3637,
	3644,
	3652,
	3661,
	3669,
	3677,
	3685,
	3690,
	3696,
	3705,
	3709,
	3714,
	3720,
	3731,
	3738,
	3743,
	3750,
	3758,
	3763,
	3771,
	3780,
	3786,
	3790,
	3804,
	3814,
	3825,
	3835,
	3845,
	3859,
	3868,
	3874,
	3882,
	3895,
	3904,
	3909,
	3913,
};

#define SCANKEYWORDS_NUM_KEYWORDS 504

static int
ScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1009] = {
		   397,   -127,    467,  32767,  32767,     56,    466,   -361,
		 32767,   -259,    465,  32767,  32767,      0,  32767,      0,
		     0,     97,    -79,   -393,   -386,   -367,  32767,  32767,
		     0,    541,  32767,   -118,     16,  32767,  32767,   -327,
		 32767,     89,  32767,      0,   -597,      0,    213,  32767,
		 32767,     94,      0,  32767,  32767,    227,  32767,   -117,
		    23,    404,    518,  32767,  32767,     29,  32767,     42,
		   572,  32767,  32767,  32767,  32767,    269,  32767,    677,
		  -303,    490,   -370,  32767,    286,    406,    413,  32767,
		 32767,     -6,  32767,    201,  32767,  32767,    155,  32767,
		 32767,  32767,  32767,    369,   -240,    192,      0,    142,
		   -98,  32767,  32767,    -22,  32767,  32767,    480,      0,
		     0,    524,    242,    446,  32767,  32767,   -359,    328,
		 32767,  32767,  32767,  32767,    443,    640,  32767,    255,
		   444,   -148,  32767,    449,      0,  32767,  32767,   -373,
		   485,  32767,    470,      0,   -515,   -665,    427,    652,
		   354,  32767,    407,    366,  32767,   -271,  32767,   -229,
		   342,    185,    484,      0,  32767,      0,  32767,    318,
		 32767,    291,  32767,      0,    -49,  32767,    349,    171,
		 32767,  32767,  32767,  32767,  32767,    677,    290,    491,
		   666,      0,      0,  32767,    335,    335,    344,  32767,
		   135,  32767,  32767,  32767,    -54,  32767,   -343,  32767,
		   323,      0,    113,  32767,     71,    447,    191,  32767,
		 32767,    129,  32767,    668,   -222,  32767,  32767,    -51,
		 32767,     62,    300,    149,  32767,  32767,    158,     45,
		 32767,    130,   -279,  32767,    153,    754,   -768,  32767,
		 32767,  32767,    392,      0,   -247,  32767,      0,    494,
		 32767,    607,     53,   -191,     59,    -66,    -38,  32767,
		     0,    419,  32767,  32767,  32767,      0,  32767,    417,
		     0,    253,  32767,    187,      0,   -645,  32767,  32767,
		  -486,  32767,  32767,  32767,  32767,   -210,    -73,      0,
		 32767,  32767,    143,  32767,   -237,     -4,  32767,  32767,
		 32767,    109,  32767,    601,    581,  32767,  32767,    247,
		 32767,    272,    135,      0,      5,    168,    -14,  32767,
		 32767,   -441,  32767,   -109,      0,    281,  32767,      0,
		 32767,   -356,   -395,  32767,     51,  32767,  32767,    -26,
		 32767,  32767,    188,   -492,    -90,    256,    153,    658,
		   350,    117,   -250,  32767,  32767,  32767,    202,  32767,
		 32767,    368,   -297,    190,  32767,   -310,     67,    214,
		   425,  32767,  32767,    205,  32767,    839,   -244,      0,
		 32767,     -3,   -311,   -471,  32767,    801,   -429,  32767,
		     0,      0,  32767,      0,      0,  32767,   -222,  32767,
		   -31,  32767,      0,   -463,  32767,    179,   -289,      0,
		 32767,      0,    626,  32767,    415,      0,  32767,    426,
		     0,  32767,  32767,    -29,    784,  32767,   -352,  32767,
		 32767,  32767,  32767,    448,  32767,    482,    347,  32767,
		 32767,  32767,  32767,  32767,    103,      0,     54,  32767,
		   463,  32767,   -329,      0,    168,   -263,  32767,  32767,
		   210,   -352,  32767,    301,    -50,     37,  32767,      0,
		 32767,      0,    324,  32767,      0,  32767,    239,    276,
		   220,   -443,    -99,    456,      0,    931,      0,    133,
		     0,    232,  32767,    397,  32767,  32767,   -371,  32767,
		   431,  32767,    534,  32767,  32767,     56,    497,    209,
		 32767,    360,    260,      0,  32767,  32767,    255,  32767,
		  -240,    395,     73,   -139,  32767,  32767,      0,  32767,
		   190,     86,    123,    110,  32767,  32767,    270,    277,
		   734,      0,    320,    342,      0,    348,  32767,  32767,
		   213,  32767,  32767,      0,    216,    120,    464,  32767,
		  -145,    319,     11,      0,    284,     93,    229,  32767,
		  -623,  32767,  32767,  32767,    656,  32767,      0,    653,
		  -247,      0,    407,    578,   -233,  32767,    249,      0,
		   796,  32767,     16,    445,  32767,    -13,      0,    598,
		   306,  32767,  32767,    -94,  32767,    -74,      0,  32767,
		 32767,  32767,      0,    -97,      0,    462,    475,      0,
		   322,    491,    296,  32767,    414,   -208,   -459,    130,
		   420,  32767,     40,  32767,  32767,  32767,     77,     47,
		   152,    121,  32767,  32767,      0,    282,     90,      0,
		 32767,     67,  32767,      0,    331,  32767,  32767,  32767,
		     0,  32767,  32767,     19,  32767,    126,    531,   -428,
		   380,    176,   -387,     72,    283,    -76,    337,  32767,
		  -365,  32767,      7,  32767,  32767,    117,  32767,    467,
		   396,  32767,   -158,    503,    656,   -147,  32767,  32767,
		 32767,  32767,   -348,      0,    315,   -107,  32767,    441,
		     0,    310,      0,   -222,  32767,  32767,    327,      0,
		 32767,    111,    -38,    295,     78,      0,  32767,  32767,
		  -132,    135,  32767,    142,      0,    387,    432,  32767,
		     0,     50,  32767,  32767,  32767,      0,   -401,    245,
		  -128,  32767,  32767,    279,  32767,  32767,  32767,  32767,
		     0,  32767,      0,    679,   -164,  32767,  32767,  32767,
		   117,    386,   -183,  32767,    374,   -268,  32767,      0,
		 32767,    -88,    481,   -223,  32767,    299,     35,  32767,
		 32767,    726,    297,      3,  32767,    505,  32767,    348,
		  -344,    321,    948,     47,    734,    111,      0,    225,
		   293,    290,     96,   -365,   -310,  32767,    389,    -95,
		   234,  32767,   -348,    118,  32767,    152,  32767,  32767,
		     0,      0,  32767,      0,  32767,  32767,  32767,      0,
		   100,    389,    386,  32767,   -601,      0,    502,  32767,
		   -72,      0,   -364,    134,    253,    471,   -173,    164,
		   655,  32767,      0,  32767,  32767,      0,     61,  32767,
		  -129,    472,  32767,   -259,      0,    207,      0,  32767,
		 32767,     79,      0,    490,    118,    383,  32767,    165,
		 32767,    515,  32767,    341,      0,      0,  32767,    473,
		 32767,  32767,  32767,  32767,    256,    178,   -415,    305,
		   518,    178,    483,   -168,    425,    467,    171,  32767,
		 32767,    468,  32767,    170,  32767,  32767,  32767,     36,
		     0,  32767,    185,  32767,      0,    206,  32767,    127,
		   321,    351,   -383,    112,  32767,    455,    246,  32767,
		    -2,      0,  32767,      0,  32767,   -379,     47,  32767,
		 32767,    213,      0,    287,      0,  32767,  32767,      0,
		 32767,    238,  32767,  32767,    492,    167,  32767,   -262,
		 32767,   -641,  32767,    423,  32767,    469,  32767,  32767,
		  -238,   -164,    -74,  32767,    146,    132,    917,   -612,
		     0,  32767,  32767,    233,     97,    140,  32767,      0,
		 32767,    583,  32767,     49,    -30,  32767,    202,      0,
		 32767,   -492,    459,  32767,    329,  32767,     83,    469,
		 32767,    -67,   -315,    485,  32767,  32767,    308,   -488,
		     0,      0,      0,    461,    341,  32767,  32767,   -330,
		     0,    154,      0,  32767,    150,  32767,    415,  32767,
		    94,   -330,    404,      0,  32767,  32767,      0,    370,
		     0,  32767,    125,  32767,   -160,  32767,    429,    264,
		 32767,  32767,  32767,  32767,    384,     31,    215,  32767,
		   241,  32767,    102,      0,      0,  32767,  32767,      0,
		   -29,      0,  32767,      0,  32767,    412,  32767,    172,
		     0,  32767,    300,   -309,    217,      0,      0,     35,
		     0,    163,  32767,    426,      0,   -455,    782,    349,
		     0,     57,   -308,    396,     26,      0,    623,     29,
		 32767,     84,  32767,    622,  32767,    345,  32767,  32767,
		     0,      0,  32767,     52,   -315,      8,    179,  32767,
		     0,     79,  32767,  32767,  32767,      0,    265,    327,
		   479,    292,  32767,      0,  32767,  32767,    578,     15,
		   106,    117,  32767,      0,  32767,    164,    437,   -165,
		     0,  32767,      0,  32767,  32767,      0,      0,  32767,
		 32767,    787,     98,    163,    387,    273,      0,  32767,
		   194,  32767,    381,      0,    286,  32767,  32767,  32767,
		  -670,      0,  32767,    749,      0,  32767,    250,  32767,
		 32767,      0,  32767,      0,  32767,  32767,    400,  32767,
		     0,
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 1;
	uint32		b = 4;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 31 + c;
		b = b * 127 + c;
	}
	return h[a % 1009] + h[b % 1009];
}

const ScanKeywordList ScanKeywords = {
	ScanKeywords_kw_string,
	ScanKeywords_kw_offsets,
	ScanKeywords_hash_func,
	SCANKEYWORDS_NUM_KEYWORDS,
	19
};

#endif							/* KWLIST_D_H */
